

server:
  port: 8082

dubbo:
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.8.162:2181
  #zk\u5185\u90E8\u7AEF\u53E3\u4FEE\u6539   \u9ED8\u8BA4\u4E3A 20800
  protocol:
    port: 12398